apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rust-web-server
  template:
    metadata:
      labels:
        app: rust-web-server
    spec:
      containers:
      - name: rust-web-server
        image: 499974397304.dkr.ecr.eu-west-1.amazonaws.com/temp-to-be-deleted
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rust-web-server
spec:
  type: LoadBalancer  # Change to LoadBalancer if you're using a cloud provider
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000  # Optional: specify a nodePort if needed
  selector:
    app: rust-web-server

